name: Update Data

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # allows manual triggering if needed

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch Data from FRED
        run: node fetch_data.js
        env:
          FRED_API_KEY: ${{ secrets.FRED_KEY }}

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          # Check if there are changes to commit
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          else
            git commit -m "Update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
